languages:
  JavaScript: true
exclude_paths:
- "src/array-cop.min.js"
- "test/array-cop.test.js"
engines:
  # ... CONFIG CONTENT ...
  eslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      complexity:
        enabled: false
      Similar code:
        enabled: false
# ... CONFIG CONTENT ...
